"""create schedule break and blocked period tables

Revision ID: 2c2698643d24
Revises: 9e20e53c0c6e
Create Date: 2026-09-23 19:41:10.826186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2698643d24'
down_revision: Union[str, Sequence[str], None] = '9e20e53c0c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('blocked_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_periods_barber_id'), 'blocked_periods', ['barber_id'], unique=False)
    op.create_index(op.f('ix_blocked_periods_blocked_date'), 'blocked_periods', ['blocked_date'], unique=False)
    op.create_index(op.f('ix_blocked_periods_id'), 'blocked_periods', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_day_off', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_barber_id'), 'schedules', ['barber_id'], unique=False)
    op.create_index(op.f('ix_schedules_day_of_week'), 'schedules', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_schedule_date'), 'schedules', ['schedule_date'], unique=False)
    op.create_table('schedule_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_breaks_id'), 'schedule_breaks', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_breaks_schedule_id'), 'schedule_breaks', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_breaks_schedule_id'), table_name='schedule_breaks')
    op.drop_index(op.f('ix_schedule_breaks_id'), table_name='schedule_breaks')
    op.drop_table('schedule_breaks')
    op.drop_index(op.f('ix_schedules_schedule_date'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_day_of_week'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_barber_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_blocked_periods_id'), table_name='blocked_periods')
    op.drop_index(op.f('ix_blocked_periods_blocked_date'), table_name='blocked_periods')
    op.drop_index(op.f('ix_blocked_periods_barber_id'), table_name='blocked_periods')
    op.drop_table('blocked_periods')
    # ### end Alembic commands ###
